version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: photopea-app_server_1 
      APP_PORT: 80 

  server:
    image: dennysubke/photopea:latest
    user: "1000:1000"
    init: true
    restart: unless-stopped

