version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: photopea-app_server_1 
      APP_PORT: 80 

  server:
    image: kovaszab/photopea:latest
    user: "1000:1000"
    init: true
    restart: unless-stopped
 
 dns: 
      - 8.8.8.8 # DNS do Google
      - 1.1.1.1 # DNS da Cloudflare 

