version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: photopea-app_server_1 
      APP_PORT: 5000  

  server:
    image: shtse8/photopea:1.0
    user: "1000:1000"
    init: true
    restart: unless-stopped
